### ISSUE TITLE
interfaces.legacy_get_updates_support

### ISSUE THREAD

**Issue by xingbotao** [farizrahman4u/keras-contrib#149]
when I use the keras-contrib, meet the "module has no attribution interfaces.legacy_get_updates_support " ,why?

**Comment by thomaspheiffer** [comment]
I had the same issue. I discovered that I only had keras 2.0.5 installed in my Ubuntu environment, which seemed to be incompatible with the latest keras-contrib. I solved it by doing "pip install keras==2.0.8". 

Hope this helps.

**Comment by ahundt** [comment]
Keras-contrib is currently only designed to work either with master or the latest release, not older versions. In reality even that is true only so long as there is someone who submits a pull requests to fix things whenever they break due to changes in master. I'm closing this, but feel free to comment if there is still a problem.
